
model_name: "llama"
model_weights: "/data/shared/llama/30B/"
task: "open_qa"
max_new_tokens: 128
load_config: false
model_args:
  device_map: "auto"
tokenizer_args:
  add_eos_token: true  # for fine-tuning
  padding_side: 'left'