
model_name: "llama"
model_weights: "/data/shared/llama/13B/"
task: "open_qa"
max_new_tokens: 128
load_config: false
model_config_args:
  vocab_size: 32001
tokenizer_args:
  add_eos_token: true
  padding_side: 'left'